[prig]: update mostly done, apply in progress

diff --git a/cmd/cmd_update b/cmd/cmd_update
--- a/cmd/cmd_update
+++ b/cmd/cmd_update
@@ -24,16 +24,49 @@
 
 function prig_cmd_update # ()
 {
-  log_cmd pushd "$gbl_opt_prig_command_dir" || diecv "unable to change the directory to $gbl_opt_prig_command_dir"
+  if [ "${gbl_opt_prig_repo:0:7}" = 'file://' ]
+  then
+    echo "copying prig from '$gbl_opt_prig_repo' to '$gbl_opt_prig_command_dir'..."
+    log_cmd git rm -r --force "$gbl_opt_prig_command_dir"
+    log_cmd rm -rf "$gbl_opt_prig_command_dir"
+    log_cmd rm -rf "$(git rev-parse --git-dir)/modules/prig-submodule/"
+    log_cmd mkdir -p "$gbl_opt_prig_command_dir"
+    log_cmd cp -v "${gbl_opt_prig_repo:7}/prig" "$gbl_opt_prig_command_dir/"
+    log_cmd cp -Rv "${gbl_opt_prig_repo:7}/cmd" "$gbl_opt_prig_command_dir/"
 
-  echo 'updating prig...'
+    log_cmd git add "$gbl_opt_prig_command_dir/*" "$gbl_opt_prig_command_dir/cmd/*"
+  else
+    if ! _cmd_update_is_a_valid_submodule
+    then
+      echo 'prig not found as a submodule... checking it out.'
+      log_cmd git rm -r --force "$gbl_opt_prig_command_dir"
+      log_cmd rm -rf "$gbl_opt_prig_command_dir"
+      log_cmd git submodule add --name "prig-submodule" -- "$gbl_opt_prig_repo" "$gbl_opt_prig_command_dir"
+    else
+      log_cmd pushd "$gbl_opt_prig_command_dir" || diecv "unable to change the directory to $gbl_opt_prig_command_dir"
 
-  log_cmd git pull --rebase || diecv "unable to pull changes from the prig repository (check the logs)"
+      echo 'updating prig...'
 
-  log_cmd popd
+      log_cmd git pull --rebase || diecv "unable to pull changes from the prig repository (check the logs)"
+
+      log_cmd popd
+    fi
+  fi
 
   [ -f "./prig" ] && cmp "./prig" "$gbl_opt_prig_command_dir/prig" &>/dev/null || log_cmd cp -v "$gbl_opt_prig_command_dir/prig" .
 
   log_cmd git add ./prig "$gbl_opt_prig_command_dir"
   [ "$cmd_opt_update_commit" = "true" ] && log_cmd git commit -m "[prig]: update prig to the latest revision"
+}
+
+function _cmd_update_is_a_valid_submodule
+{
+  [ ! -d "$gbl_opt_prig_command_dir" ] && return 1
+
+  prig_repos="$(git submodule foreach 'echo -n "$path#" 1>&2 ; git remote get-url origin | tr \\n \\# 1>&2 ; echo -n "$name" 1>&2' 2>&1 1>/dev/null  | grep -F "$(echo -e "$gbl_opt_prig_repo\\nprig-submodule")")"
+  [ -z "$prig_repos" ] && return 1
+
+  [ "$(git -C "$gbl_opt_prig_command_dir" remote get-url origin)" != "$gbl_opt_prig_repo" ] && return 1
+
+  return 0
 }
